### ISSUE TITLE
bug after converting SVG shape to skia path

### ISSUE THREAD

**Issue by anthrotype** [rsheeter/playground#4]
If I run this snippet inside Trufont

```python
from nanosvg.svg import SVG
from nanosvg.svg_pathops import skia_path
from fontTools.svgLib.path import SVGPath

s = """\
<svg viewBox="0 0 128 128" 
    xmlns="http://www.w3.org/2000/svg">
<path fill="#424242" d="m34 23.25c14.68 0 26.62 18.39 26.62 41s-11.94 41-26.62 41-26.62-18.39-26.62-41 11.94-41 26.62-41z" opacity="0.2"/>
</svg>
"""

svg1 = SVG.fromstring(s)

svg2 = SVGPath.fromstring(s)

g = CurrentGlyph()
pen = g.getPen()

for shape in svg1.shapes():
   path = skia_path(shape)
   path.draw(pen)
 
svg2.draw(pen)
```

I get this:

![image](https://user-images.githubusercontent.com/6939968/75367021-8ca36780-58b7-11ea-8ecd-e0395d168292.png)

the buggy path is coming from nanosvg. I think something is up when converting from SVG to pathops.Path.

**Comment by anthrotype** [comment]
Hm.. I found that if I convert coords to absolute values before doing expand_shorthand the path draws correctly. See PR #5 

![image](https://user-images.githubusercontent.com/6939968/75368994-8793e780-58ba-11ea-83ff-988d6631a75d.png)

**Comment by rsheeter** [comment]
That fix suggests that expand_shorthand remains broken, presumably in computation of current coord as it wanders along paths. I think it would be better to fix it directly.
